name: torch-ngp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - cudatoolkit=11.7
  - ninja
  - trimesh
  - opencv
  - tensorboardX
  - pytorch
  - numpy 
  - pandas
  - tqdm
  - matplotlib
  - rich
  - packaging
  - scipy
  - pip:
    - imageio
    - lpips
    - torch-ema
    - PyMCubes
    - pysdf
    - dearpygui
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
